'use strict';
let token=null,sessionProject=null,busy=false,rows=[],selected=null,offset=0,restaurant=null,locationId=null,searchTimer=null,searchRevision=0,dirty=false;
const $=id=>document.getElementById(id);
for(const [index,name] of ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].entries()){
 const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.value=index+1;input.name='day';label.append(input,document.createTextNode(name));$('days').append(label);
}
function config(){const url=new URL($('url').value.trim());if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co')||url.username||url.password||url.port||url.search||url.hash||url.pathname!=='/')throw Error('Use the HTTPS development project URL.');const key=$('key').value.trim();let valid=key.startsWith('sb_publishable_');if(!valid)try{valid=JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon'}catch{}if(!valid)throw Error('Use only a publishable client key.');return {url:url.origin,key}}
async function request(path,body,auth=true){const {url,key}=config();if(auth&&(!token||sessionProject!==url))throw Error('Sign in to this development project first.');const headers={apikey:key,'Content-Type':'application/json'};if(auth)headers.Authorization='Bearer '+token;else if(!key.startsWith('sb_publishable_'))headers.Authorization='Bearer '+key;const response=await fetch(url+path,{method:'POST',headers,body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok){let detail='';try{detail=(await response.json()).message||''}catch{}throw Error('Request failed ('+response.status+'). '+(response.status===401?'Sign in again.':detail||'Check setup and reviewer permissions.'))}return response.json()}
function controls(){for(const button of document.querySelectorAll('button'))button.disabled=busy;for(const id of ['reload','previous','next'])$(id).disabled=busy||!token;$('previous').disabled=busy||!token||offset===0;$('next').disabled=busy||!token||rows.length<20;$('draft-fields').disabled=busy||!selected||['APPROVED','REJECTED'].includes(selected.status);}
function report(message,error=false){
 $('status').textContent=message;const inline=$('action-status');inline.textContent=message;inline.classList.remove('hidden');inline.style.borderColor=error?'#a43f31':'#6a7040';
 if(error){inline.focus({preventScroll:true});inline.scrollIntoView({block:'nearest',behavior:'smooth'})}
}
async function perform(action){if(busy)return;busy=true;controls();try{await action()}catch(error){report(error.message,true)}finally{busy=false;controls()}}
function canLeave(){return !dirty||confirm('Leave these unsaved review edits?')}
function clearEditor(){searchRevision++;clearTimeout(searchTimer);selected=null;dirty=false;$('editor').classList.add('hidden');$('empty').classList.remove('hidden');$('matches').replaceChildren()}
async function load(){const result=await request('/rest/v1/rpc/ww_review_queue',{p_status:$('filter').value,p_offset:offset});if(!Array.isArray(result))throw Error('Unexpected queue response.');rows=result;clearEditor();$('queue').replaceChildren();for(const row of rows){const button=document.createElement('button');button.className='queue-item';const title=document.createElement('strong');title.textContent=row.place;const subtitle=document.createElement('small');subtitle.textContent=row.offer.slice(0,100);button.append(title,subtitle);button.onclick=()=>{if(canLeave()){show(row);for(const other of $('queue').children)other.classList.toggle('selected',other===button)}};$('queue').append(button)}if(!rows.length){const p=document.createElement('p');p.textContent='No submissions in this status.';$('queue').append(p)}$('page').textContent=rows.length?'Entries '+(offset+1)+'–'+(offset+rows.length):'No entries';$('status').textContent='Reviewer access confirmed. '+rows.length+' submission(s) loaded.'}
function show(row){$('action-status').classList.add('hidden');searchRevision++;clearTimeout(searchTimer);selected=row;dirty=false;const d=row.draft||{};restaurant=d.restaurant_id||row.restaurant_id||null;locationId=d.location_id||row.location_id||null;$('empty').classList.add('hidden');$('editor').classList.remove('hidden');$('original-place').textContent=row.place;$('original-offer').textContent=row.offer;$('original-status').textContent=row.status.replaceAll('_',' ');$('restaurant-name').value=d.restaurant_name||row.restaurant_name||'';$('address').value=d.address||row.address||'';$('offer').value=d.offer??row.offer;$('terms').value=d.terms||'';$('source').value=d.source||'';$('note').value=d.note??row.note;$('strength').value=d.savings_rank??0;$('kids').checked=d.for_kids===true;$('weekly').checked=d.weekly_only===true;$('checked').checked=d.details_checked===true;for(const input of $('days').querySelectorAll('input'))input.checked=(d.days||[]).includes(Number(input.value));$('search').value='';$('search-status').textContent='';$('matches').replaceChildren();$('finalized').classList.toggle('hidden',!['APPROVED','REJECTED'].includes(row.status));identity();controls()}
async function existingOffers(){
 const currentLocation=locationId,currentEntry=selected?.id;$('existing-offers').classList.add('hidden');$('existing-offer-list').replaceChildren();if(!locationId)return;
 try{const offers=await request('/rest/v1/rpc/ww_review_place_offers',{p_location:locationId});if(locationId!==currentLocation||selected?.id!==currentEntry)return;
 if(offers.length){for(const offer of offers){const p=document.createElement('p');p.textContent=offer.offer+' — '+offer.terms;$('existing-offer-list').append(p)}$('existing-offers').classList.remove('hidden')}}catch(error){if(locationId===currentLocation&&selected?.id===currentEntry)$('status').textContent='Couldn’t check published offers. '+error.message}
}
function identity(){existingOffers();$('restaurant-name').readOnly=!!restaurant;$('address').readOnly=!!locationId;$('matched').classList.toggle('hidden',!restaurant);$('matched').textContent=locationId?'Existing restaurant and location selected.':'Existing restaurant selected. Enter the new location address.';$('create-location').disabled=busy||!restaurant;}
$('search').oninput=()=>{const revision=++searchRevision;const current=selected?.id;clearTimeout(searchTimer);$('matches').replaceChildren();const query=$('search').value.trim();if(query.length<2){$('search-status').textContent='Enter at least 2 letters.';return}$('search-status').textContent='Searching…';searchTimer=setTimeout(async()=>{try{const places=await request('/rest/v1/rpc/ww_search_places',{p_query:query});if(revision!==searchRevision||selected?.id!==current)return;$('search-status').textContent=places.length?'Select the correct location (up to 10 results).':'No matches. Create a missing place below.';for(const place of places){const button=document.createElement('button');button.type='button';button.className='secondary search-result';button.textContent=place.name+' — '+place.address;button.onclick=()=>{if(busy)return;restaurant=place.restaurant_id;locationId=place.location_id;$('restaurant-name').value=place.name;$('address').value=place.address;dirty=true;identity();$('matches').replaceChildren()};$('matches').append(button)}}catch(error){if(revision===searchRevision)$('search-status').textContent=error.message}},350)};
$('create-restaurant').onclick=()=>{restaurant=null;locationId=null;dirty=true;identity();$('restaurant-name').focus()};$('create-location').onclick=()=>{if(!restaurant)return;locationId=null;$('address').value='';dirty=true;identity();$('address').focus()};
function draft(){return {restaurant_id:restaurant,location_id:locationId,restaurant_name:$('restaurant-name').value.trim(),address:$('address').value.trim(),offer:$('offer').value.trim(),terms:$('terms').value.trim(),source:$('source').value.trim(),note:$('note').value.trim(),days:[...$('days').querySelectorAll('input:checked')].map(i=>Number(i.value)),for_kids:$('kids').checked,savings_rank:Number($('strength').value),weekly_only:$('weekly').checked,details_checked:$('checked').checked}}
function action(kind){perform(async()=>{if(!selected)throw Error('Choose a submission.');const d=draft();if(['CLARIFY','REJECT'].includes(kind)&&!d.note)throw Error('Add a reviewer note first.');if(kind==='APPROVE'){const missing=reviewApprovalMissing(d);if(missing.length)throw Error('Before approval, complete:\n• '+missing.join('\n• '));if(!confirm('Publish this reviewed possible deal to the development app catalog?'))return}report(kind==='APPROVE'?'Approving and publishing…':kind==='SAVE'?'Saving draft…':'Updating review…');const result=await request('/rest/v1/rpc/ww_review_submission',{p_id:selected.id,p_revision:selected.revision,p_action:kind,p_draft:d});dirty=false;if(kind==='SAVE'){selected={...selected,draft:d,revision:result.revision};report('Review draft saved. Original contribution preserved.')}else{const success=kind==='APPROVE'?'Approved as a possible deal. Refresh the app to see it.':'Review status updated.';try{await load();report(success)}catch(_){report(success+' Couldn’t refresh the queue; reload it to see the updated status.')}}})}
for(const [id,kind] of [['save','SAVE'],['clarify','CLARIFY'],['reject','REJECT'],['approve','APPROVE']])$(id).onclick=()=>action(kind);
$('editor').onsubmit=e=>e.preventDefault();$('draft-fields').addEventListener('input',()=>{dirty=true});
$('login').onsubmit=e=>{e.preventDefault();perform(async()=>{token=null;sessionProject=null;clearEditor();$('queue').replaceChildren();const data=await request('/auth/v1/token?grant_type=password',{email:$('email').value.trim(),password:$('password').value},false);token=data.access_token;sessionProject=config().url;$('password').value='';offset=0;await load();$('connection').open=false})};
$('logout').onclick=()=>{if(!canLeave())return;token=null;sessionProject=null;rows=[];clearEditor();$('queue').replaceChildren();$('password').value='';$('status').textContent='Signed out locally.';$('connection').open=true;controls()};
$('reload').onclick=()=>{if(canLeave())perform(load)};$('filter').onchange=()=>{if(canLeave()){offset=0;perform(load)}else if(selected)$('filter').value=selected.status};$('previous').onclick=()=>{if(canLeave()){offset=Math.max(0,offset-20);perform(load)}};$('next').onclick=()=>{if(canLeave()){offset+=20;perform(load)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});controls();
